local obj1 = {
	["conditions"] = {},
	["items"] = {
		["Amber"] = "Buy",
		["Bat Wing"] = "Buy",
		["Black Ceremonial Coffin"] = "Buy",
		["Black Pearl"] = "Buy",
		["Bloodstone"] = "Buy",
		["Bone Chips"] = "Buy",
		["Cat's Eye Agate"] = "Buy",
		["Cloudy Stone of Veeshan"] = "Buy",
		["Emerald"] = "Buy",
		["Fish Scales"] = "Buy",
		["Fuligan Soulstone of Innoruuk"] = "Buy",
		["Jade"] = "Buy",
		["Jade Inlaid Coffin"] = "Buy",
		["Jasper"] = "Buy",
		["Malachite"] = "Buy",
		["Opal"] = "Buy",
		["Pearl"] = "Buy",
		["Peridot"] = "Buy",
		["Snake Scales"] = "Buy",
		["Star Rose Quartz"] = "Buy",
		["Tiny Jade Inlaid Coffin"] = "Buy",
		["Topaz"] = "Buy",
	},
}
return obj1
